name: 'emqx-stack'
services:
  ## MQTT Broker
  emqx-broker:
    image: ${REGISTRY_NAME}/${EMQX_CONTAINER_NAME}:${EMQX_CONTAINER_TAG}
    container_name: ${EMQX_CONTAINER_NAME}
    network_mode: host
    # ports:
    #   - "1883:1883"       # MQTT
    #   - "8883:8883"       # MQTT over TLS
    #   - "8083:8083"       # MQTT over WebSocket
    #   - "18083:18083"     # Dashboard HTTP
    environment:
      EMQX_CLUSTER__NAME: ${EMQX_CLUSTER__NAME}
      EMQX_NODE__NAME: ${EMQX_NODE__NAME}
      EMQX_NODE__COOKIE: ${EMQX_NODE__COOKIE}
      EMQX_DASHBOARD__DEFAULT_PASSWORD: ${EMQX_DASHBOARD__DEFAULT_PASSWORD}
      EMQX_LOG__CONSOLE__LEVEL: ${EMQX_LOG__CONSOLE__LEVEL}
    volumes:
      - emqx_data:/opt/emqx/data
    # Loggin settings
    logging:
      driver: "json-file"
      options:
        max-size: "8m"
        max-file: 4
        compress: "true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18083/status"]
      retries: 6
      interval: 10s
      timeout: 5s
    depends_on:
      postgresql-broker:
        condition: service_healthy
    restart: always
  ## Postgresql
  postgresql-broker:
    image: ${REGISTRY_NAME}/${POSTGRES_CONTAINER_NAME}:${POSTGRES_CONTAINER_TAG}
    container_name: ${POSTGRES_CONTAINER_NAME}
    network_mode: host
    # Volumes
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    # Environment variables
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_ADMIN_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_ADMIN_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      PGPORT: ${PGPORT}
      PGDATA: /var/lib/postgresql/data
      POSTGRESQL_CONF_FILE: /etc/postgresql/postgresql.conf
      PG_HBA_FILE: /etc/postgresql/pg_hba.conf
    # Loggin settings
    logging:
      driver: "json-file"
      options:
        max-size: "8m"
        max-file: 4
        compress: "true"
    restart: always
    # Check status of service
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "$POSTGRES_DB"]
      retries: 12
      interval: 5s
      timeout: 5s


# Volumes
volumes:
  emqx_data:
    name: emqx_data
    driver: local
  postgresql_data:
    name: postgresql_data
    driver: local

